monitor.bluez.rules = [
  {
    matches = [
      {
        node.name = "bluez_output.88_92_CC_E4_81_60.1"
      }
    ]
    actions = {
      update-props = {
        node.autoconnect = true
      }
    }
  }
]
