#!/bin/bash

DIR=~/Videos/Screenrecs
mkdir -p "$DIR"
PIDFILE="/tmp/screenrec.pid"

if [[ -f "$PIDFILE" ]]; then
    kill "$(cat "$PIDFILE")"
    rm "$PIDFILE"
    notify-send "Screen Recording" "Stopped" --icon=video-x-generic
else
    COUNT=$(ls -1q "$DIR"/*.mp4 2>/dev/null | wc -l)
    FILE="$DIR/rec_$(date +'%Y-%m-%d')-$(printf '%04d' $COUNT).mp4"
    RESOLUTION=$(xdpyinfo | awk '/dimensions/{print $2}')
    ffmpeg -y -video_size "$RESOLUTION" -framerate 60 -f x11grab -i :0 \
        -c:v libx264 -preset ultrafast -pix_fmt yuv420p "$FILE" &> /dev/null &
    echo $! > "$PIDFILE"
    notify-send "Screen Recording" "Started" --icon=video-x-generic
fi

