#!/bin/bash

# Flash effect using xrandr
xrandr --output $(xrandr | grep " connected" | cut -f1 -d " ") --brightness 2
sleep 0.1
xrandr --output $(xrandr | grep " connected" | cut -f1 -d " ") --brightness 1

# Take a screenshot
scrot "$HOME/Pictures/screenshot_%Y-%m-%d_%H-%M-%S.png"
