require("tda.core.lazy")
require("tda.core.options")
require("tda.core.keymaps")
require("tda.core.autocmds")
require("tda.core.reload")

require("tda.plugins.nightfox")
require("tda.plugins.cmp")
require("tda.plugins.lsp")
require("tda.plugins.format")
require("tda.plugins.oil")
require("tda.plugins.treesitter")
require("tda.plugins.ibl")
require("tda.plugins.telescope")
require("tda.plugins.fugitive")
require("tda.plugins.luasnip")
